name: Build and Deploy HUGO Website
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: GIT Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Dart Sass Embedded # Installs dart-sass
        run: sudo snap install dart-sass
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true
      - name: Cache Hugo
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-            
      - name: Build Blog
        run: |
          cd lawrencecarltan
          hugo --minify
      # DEPLOY TO REMOTE SERVER
      #- name: Install SSH Key
      #  uses: shimataro/ssh-key-action@v2
      #  with:
      #    key: ${{ secrets.DEPLOY_KEY }} 
      #    known_hosts: 'placeholder'
      #- name: Adding Known Hosts
      #  run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST_IP }} >> ~/.ssh/known_hosts
      #- name: Deploy with rsync
      #  run: rsync -avz --delete ./lawrencecarltan/public/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST_IP }}:${{ secrets.DEPLOY_PATH }}      
      # Trial for AWS SSM Connectivity
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
      - name: Deploy via SSM (direct copy)
        run: |
          cd ./lawrencecarltan/public/
          zip -r public.zip .
          b64=$(base64 public.zip | tr -d '\n')

          aws ssm send-command \
            --instance-ids "${{ secrets.INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'echo ${b64} | base64 -d > /tmp/public.zip',
              'sudo unzip -o /tmp/app.zip -d /var/www/test/'
            ]"
