name: Build and Deploy HUGO Website
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: GIT Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Dart Sass Embedded # Installs dart-sass
        run: sudo snap install dart-sass
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true
      - name: Cache Hugo
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-            
      - name: Build Blog
        run: |
          cd lawrencecarltan
          hugo --minify
      # DEPLOY TO REMOTE SERVER
      #- name: Install SSH Key
      #  uses: shimataro/ssh-key-action@v2
      #  with:
      #    key: ${{ secrets.DEPLOY_KEY }} 
      #    known_hosts: 'placeholder'
      #- name: Adding Known Hosts
      #  run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST_IP }} >> ~/.ssh/known_hosts
      #- name: Deploy with rsync
      #  run: rsync -avz --delete ./lawrencecarltan/public/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST_IP }}:${{ secrets.DEPLOY_PATH }}      
      # Trial for AWS SSM Connectivity
      - name: Configure AWS credentials in Github runner
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
      - name: Package application
        run: |
          cd ./lawrencecarltan/public/
          zip -r public.zip .
      - name: Upload package to S3
        run: |
          cd ./lawrencecarltan/public/
          aws s3 cp public.zip s3://lawrencetanio-artifactory/public.zip
      - name: Configure AWS credentials in target host
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
      - name: Deploy to EC2 via SSM
        id: execute_command
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.PROD_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy new version from GitHub" \
            --parameters 'commands=[
              "cd /var/www/lawrencetan.io/public",
              "sudo aws s3 cp s3://lawrencetanio-artifactory/public.zip .",
              "sudo unzip -o public.zip",
              "sudo rm /var/www/lawrencetan.io/public/public.zip",
              "sudo systemctl restart httpd"
            ]' \
            --query "Command.CommandId" \
            --output text)
          echo "Command ID: $COMMAND_ID"
          echo "::set-output name=command_id::$COMMAND_ID"    
      - name: Output execution via SSM
        id : output_execution
        run: |
          sleep 15s
          COMMAND_ID=${{ steps.execute_command.outputs.command_id }}
          aws ssm list-command-invocations \
            --details \
            --instance-id ${{ secrets.PROD_INSTANCE_ID }} \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,Output:Output}" \
            --command-id "$COMMAND_ID" \
            --output text
